# Verbose Quantization Configuration
model:
  model_name: "microsoft/DialoGPT-small"
  tokenizer_name: "microsoft/DialoGPT-small"
  trust_remote_code: false

method: "q8_0"
output_path: "verbose_test.gguf"
output_format: "gguf"
batch_size: 16
verbose: true
